ThoiTrangGiayCaoCap/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyClass.DAO;
using MyClass.Models;

namespace ThoiTrangGiayCaoCap.Controllers
{
    public class ModuleController : Controller
    {
        private MenuDAO menuDAO = new MenuDAO();
        private SliderDAO sliderDAO = new SliderDAO();
        private CategoryDAO categoryDAO = new CategoryDAO();
        // GET: Module
        public ActionResult MainMenu()
        {
            List<Menu> list = menuDAO.getListByParentID("mainmenu",0);
            return View("MainMenu", list);
        }
        public ActionResult MainMenuSub(int id)
        {
            Menu menu = menuDAO.getRow(id);
            List<Menu> list = menuDAO.getListByParentID("mainmenu",id);
            if(list.Count==0)
            {
                return View("MainMenuSub1", menu);//Không có cấp con
            }
            else
            {
                ViewBag.Menu = menu;
                return View("MainMenuSub2", list);//có cấp con
            }
        }
        //Slide Show
        public ActionResult Slideshow()
        {
            List<Slider> list = sliderDAO.getListByPosition("Slideshow");
            return View("Slideshow",list);
        }

        //ListCategory
        public ActionResult ListCategory()
        {
            List<Category> list = categoryDAO.getListByParentId(0);
            return View("ListCategory",list);
        }
        public ActionResult PostLastNews()
        {
            return View("PostLastNews");
        }
        public ActionResult MenuFooter()
        {
            List<Menu> list = menuDAO.getListByParentID("footermenu", 0);
            return View("MenuFooter", list);
        }
    }
}

ThoiTrangGiayCaoCap/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyClass.Models;
using MyClass.DAO;
using PagedList;

namespace ThoiTrangGiayCaoCap.Controllers
{
    public class SiteController : Controller
    {
        private LinkDAO linkDAO = new LinkDAO();
        private PostDAO postDAO = new PostDAO();
        private ProductDAO productDAO = new ProductDAO();
        private CategoryDAO categoryDAO = new CategoryDAO();
        private TopicDAO topicDAO = new TopicDAO();
        // GET: Site
        public ActionResult Index(string slug=null, int? page=null)
        {
            if(slug==null)
            {
                return this.Home();
            }
            else
            {
                Link link = linkDAO.getRow(slug);
                if(link!=null)
                {
                    string typelink = link.TypeLink;
                    switch(typelink)
                    {
                        case "category":
                            {
                                return this.ProductCategory(slug, page);
                            }
                        case "topic":
                            {
                                return this.PostTopic(slug, page);
                            }
                        case "page":
                            {
                                return this.PostPage(slug);
                            }
                        default:
                            {
                                return this.Error404(slug);
                            }
                    }    
                }  
                else
                {
                    Product product = productDAO.getRow(slug);
                    if(product!=null)
                    {
                        return this.ProductDetail(slug);
                    }
                    else
                    {
                        Post post = postDAO.getRow(slug, "Post");
                        if(post!=null)
                        {
                            return this.PostDetail(post);
                        }
                        else
                        {
                            return this.Error404(slug);
                        }
                    }
                }
            }
        }
        private ActionResult Home()
        {
            List<Category> list = categoryDAO.getListByParentId(0);
            return View("Home",list);
        }
        public ActionResult HomeProduct(int id)
        {
            Category category = categoryDAO.getRow(id);
            ViewBag.Category = category;
            //3 cấp
            List<int> listcatid = new List<int>();
            listcatid.Add(id);//Cấp 1
            List<Category> listcategory2 = categoryDAO.getListByParentId(id);
            if(listcategory2.Count()!=0)
            {
                foreach(var category2 in listcategory2)
                {
                    listcatid.Add(category2.Id);//Cấp 2
                    List<Category> listcategory3 = categoryDAO.getListByParentId(category2.Id);
                    if(listcategory3.Count() != 0)
                    {
                        foreach(var category3 in listcategory3)
                        {
                            listcatid.Add(category3.Id);//Cấp 3
                        }    
                    }    

                }
            }    
            List<ProductInfo> list = productDAO.getListByListCatId(listcatid, 4);
            return View("HomeProduct",list);
        }
        public ActionResult Product(int? page)
        {
            int pageSize = 9;
            int pageNumber = page ?? 1;
            IPagedList<ProductInfo> list = productDAO.getList(pageSize, pageNumber);
            return View("Product",list);
        }
        public ActionResult Post(int? page)
        {
            List<PostInfo> list = postDAO.getList("Post");
            return View("Post", list);
        }
        private ActionResult ProductCategory(string slug, int? page)
        {
            int pageSize = 6;
            int pageNumber = page ?? 1;
            Category category = categoryDAO.getRow(slug);
            ViewBag.Category = category;
            //3 cấp
            List<int> listcatid = new List<int>();
            listcatid.Add(category.Id);//Cấp 1
            List<Category> listcategory2 = categoryDAO.getListByParentId(category.Id);
            if (listcategory2.Count() != 0)
            {
                foreach (var category2 in listcategory2)
                {
                    listcatid.Add(category2.Id);//Cấp 2
                    List<Category> listcategory3 = categoryDAO.getListByParentId(category2.Id);
                    if (listcategory3.Count() != 0)
                    {
                        foreach (var category3 in listcategory3)
                        {
                            listcatid.Add(category3.Id);//Cấp 3
                        }
                    }

                }
            }
            IPagedList<ProductInfo> list = productDAO.getListByListCatId(listcatid, pageSize, pageNumber);
            return View("ProductCategory",list);
        }
        private ActionResult ProductDetail(string slug)
        {
            int take = 8;
            var row = productDAO.getRow(slug);
            Category category = categoryDAO.getRow(slug);
            //3 cấp
            List<int> listcatid = new List<int>();
            int catid = row.Catid;
            listcatid.Add(catid);//Cấp 1
            List<Category> listcategory2 = categoryDAO.getListByParentId(catid);
            if (listcategory2.Count() != 0)
            {
                foreach (var category2 in listcategory2)
                {
                    listcatid.Add(category2.Id);//Cấp 2
                    List<Category> listcategory3 = categoryDAO.getListByParentId(category2.Id);
                    if (listcategory3.Count() != 0)
                    {
                        foreach (var category3 in listcategory3)
                        {
                            listcatid.Add(category3.Id);//Cấp 3
                        }
                    }

                }
            }
            List<ProductInfo> listother = productDAO.getListByListCatId(listcatid, take, row.Id,  true);
            ViewBag.Listother = listother;
            return View("ProductDetail", row);
        }
        private ActionResult PostTopic(string slug, int? page)
        {
            Topic topic = topicDAO.getRow(slug);
            ViewBag.Topic = topic;
            List<PostInfo> list = postDAO.getListByTopId(topic.Id, "Post", null);
            return View("PostTopic",list);
        }
        private ActionResult PostPage(string slug)
        {
            Post post = postDAO.getRow(slug,"page");
            return View("PostPage", post);
        }
        public ActionResult PostDetail(Post post)
        {
            ViewBag.ListOther = postDAO.getListByTopId(post.TopId,"Post",post.Id); 
            return View("PostDetail",post);
        }
        private ActionResult Error404(string slug)
        {
            return View("Error404");
        }
    }
}

ThoiTrangGiayCaoCap/Views/Site/Error404.cshtml
@{
    ViewBag.Title = "Error404";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>Error404</h2>

ThoiTrangGiayCaoCap/Views/Site/Home.cshtml
@model IEnumerable<MyClass.Models.Category>

@{
    ViewBag.Title = "Trang Chủ";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

@Html.Action("Slideshow", "Module")
<!-- banner -->
<!-- content -->

<section class="content3">
    <!-- product-nav -->

    <div class="product-easy">
        <div class="container">
            <script src="~/Public/js/easyResponsiveTabs.js"></script>
            <script src="~/Public/js/easyResponsiveTabs.js" type="text/javascript"></script>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#horizontalTab').easyResponsiveTabs({
                        type: 'default', //Types: default, vertical, accordion
                        width: 'auto', //auto or any width like 600px
                        fit: true   // 100% fit in a container
                    });
                });

            </script>
            <div class="sap_tabs">
                <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
                    @foreach (var category in Model)
                    {
                        @Html.Action("HomeProduct", "Site", new { @id = category.Id })


                    }
                </div>
            </div>
        </div>
        <div class="container" style="margin-top:40px">
            <div class="row">
                <div class="col-md-8">
                </div>
                <div class="col-md-4">
                    <a href="~/tat-ca-san-pham" style="color:#069191;font-size:20px">
                        XEM TOÀN BỘ SẢN PHẨM
                        <i class="glyphicon glyphicon-arrow-right" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- //product-nav -->

</section>

ThoiTrangGiayCaoCap/Views/Site/HomeProduct.cshtml
@model IEnumerable<MyClass.Models.ProductInfo>
@{
    var category = ViewBag.Category;
}
@if(Model.Count()!=0)
            {

            
<div class="container">
    <h2 class=" text-uppercase" style="margin-bottom:20px;margin-top:60px;text-align:center;color:#111b8c;font-weight:700">
        @category.Name
    </h2>
    <a class="float-end position-absolute top-0 end-0" style="float:right;padding-bottom:20px" href="~/@category.Slug">
        XEM TẤT CẢ
    </a>
</div>

<div class="contanier">
    @foreach (var proinfo in Model)
    {
        <div class="col-md-3 product-men">
            <div class="men-pro-item simpleCart_shelfItem">

                <div class="men-thumb-item">
                    <img src="~/Public/images/Products/@proinfo.Img" alt="" class="pro-image-front">
                    <img src="~/Public/images/Products/@proinfo.Img" alt="" class="pro-image-back">
                    <div class="men-cart-pro">
                        <div class="inner-men-cart-pro">
                            <a href="~/@proinfo.Slug" class="link-product-add-cart">XEM SẢN PHẨM</a>
                        </div>
                    </div>
                    <span class="product-new-top">New</span>

                </div>
                <div class="item-info-product ">
                    <h4><a href="~/@proinfo.Slug">@proinfo.Name</a></h4>
                    <div class="info-product-price">
                        <span class="item_price">@string.Format("{0:0,0}",proinfo.Pricesale) <sup>đ</sup></span>
                        <del class="text-danger">@string.Format("{0:0,0}", proinfo.Price)</del><sup>đ</sup>
                    </div>
                    <a href="@Url.Action("CartAdd","Giohang",new { productid = proinfo.Id})" class="item_add single-item hvr-outline-out button2 text-uppercase">
                        <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i> Mua </a>
                </div>

            </div>
        </div>
    }
        <div class="clearfix"></div>
  
</div>

}

ThoiTrangGiayCaoCap/Views/Site/Khac.cshtml
@{
    ViewBag.Title = "Khac";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>Khac</h2>

ThoiTrangGiayCaoCap/Views/Site/Post.cshtml
    @model IEnumerable<MyClass.Models.PostInfo>
@{
    ViewBag.Title = "TẤT CẢ BÀI VIẾT";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<section class="maincontent clearfix">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="post-title position-relative">
                    <h2 class="text-center" style="padding-bottom:30px;padding-top:20px;color:#0ce605;font-weight:700">TẤT CẢ BÀI VIẾT</h2>
                </div>
                @foreach (var post in Model)
                {
                    <div class="row" style="margin-bottom:40px;">
                        <div class="col-md-6">
                            <a href="~/@post.Slug"><img src="~/Public/images/Post/@post.Img" class="img-fluid" /></a>
                        </div>
                        <div class="col-md-6">
                            <h3 class="text-center" style="color:red;padding-bottom:10px"><a href="~/@post.Slug">@post.Title</a></h3>
                            <p>@XString.Str_Limit(post.Detail,500)</p>
                            <div class="text-right"><a href="~/@post.Slug">Xem Thêm</a></div>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</section>

ThoiTrangGiayCaoCap/Views/Site/PostDetail.cshtml
@model MyClass.Models.Post

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}


<section class="maincontent clearfix">
    <div class="container my-3">
        <div class="row" style="margin-bottom:20px">
            <div class="col-md-12 col-lg-12">
                <h1 class="title-post" style="padding-bottom:20px;padding-top:20px;color:#4f824d">@Model.Title</h1>
                <img src="~/Public/images/Post/@Model.Img" class="img-fluid" />
                <p style="padding-top:20px">@Html.Raw(Model.Detail)</p>
            </div>
        </div>
        <div class="row" style="margin-bottom:20px">
            <div class="col-12">
                <h3 style="padding-bottom:20px;color:#4f824d">BÀI VIẾT KHÁC</h3>
                <ul>
                    @foreach (var post in ViewBag.ListOther)
                    {
                        <li> <a href="~/@post.Slug">@post.Title</a></li>

                    }
                </ul>
               
            </div>
        </div>
    </div>
</section>

ThoiTrangGiayCaoCap/Views/Site/PostPage.cshtml
@model MyClass.Models.Post

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}


<section class="maincontent clearfix">
    <div class="container my-3">
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <h1 class="title-post text-center" style="padding-bottom:40px;padding-top:40px;color:#0ce605;font-weight:700">@Model.Title</h1>
                <div class="row" style="margin-bottom:40px">
                    <div class="col-md-5">
                        <img src="~/Public/images/Post/@Model.Img" />
                    </div>
                    <div class="col-md-7">
                        <p>@Html.Raw(Model.Detail)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

ThoiTrangGiayCaoCap/Views/Site/PostTopic.cshtml
@model IEnumerable<MyClass.Models.PostInfo>
    @{ 
        var topic = ViewBag.Topic;
    }
@{
    ViewBag.Title = topic.Name;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<section class="maincontent clearfix">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="post-title position-relative">
                    <h2 class="text-center" style="padding-bottom:30px;padding-top:20px;color:#0ce605;font-weight:700">@topic.Name</h2>
                </div>
                @foreach (var post in Model)
                {
                    <div class="row" style="margin-bottom:40px;">
                        <div class="col-md-6">
                            <a href="~/@post.Slug"><img src="~/Public/images/Post/@post.Img" class="img-fluid" /></a>
                        </div>
                        <div class="col-md-6">
                            <h3 class="text-center" style="color:red;padding-bottom:10px"><a href="~/@post.Slug">@post.Title</a></h3>
                            <p>@XString.Str_Limit(post.Detail, 500)</p>
                            <div class="text-right"><a href="~/@post.Slug">Xem Thêm</a></div>
                        </div>
                    </div>

                }
            </div>
            <div class="container" style="margin-top:40px;margin-bottom:30px">
                <div class="row">
                    <div class="col-md-8">
                    </div>
                    <div class="col-md-4">
                        <a href="~/tat-ca-bai-viet" style="color:#069191;font-size:20px">
                            XEM TOÀN BỘ BÀI VIẾT
                            <i class="glyphicon glyphicon-arrow-right" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

ThoiTrangGiayCaoCap/Views/Site/Product.cshtml
@model PagedList.IPagedList<MyClass.Models.ProductInfo>

@{
    ViewBag.Title = "Tất Cả Sản Phẩm";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@using PagedList.Mvc;
<section class="maincontent clearfix">
    <div class="container my-3">
        <div class="row">
            @Html.Action("ListCategory", "Module")
            @Html.Action("PostLastNews", "Module")
            <div class="col-md-9">
                <!-- product-nav -->
                <div class="product-easy">
                    <script src="~/Public/js/easyResponsiveTabs.js"></script>
                    <script src="~/Public/js/easyResponsiveTabs.js" type="text/javascript"></script>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $('#horizontalTab').easyResponsiveTabs({
                                type: 'default', //Types: default, vertical, accordion
                                width: 'auto', //auto or any width like 600px
                                fit: true   // 100% fit in a container
                            });
                        });
                    </script>
                    <div class="sap_tabs">
                        <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
                            <ul class="resp-tabs-list">
                                <li class="resp-tab-item " style="font-weight:700;color:#111b8c;text-transform: uppercase" aria-controls="tab_item-0" role="tab"><span>TẤT CẢ SẢN PHẨM</span></li>
                            </ul>
                            <div class="resp-tabs-container">
                                <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
                                    @foreach (var proinfo in Model)
                                    {
                                        <div class="col-md-4 product-men" style="margin-bottom:30px">
                                            <div class="men-pro-item simpleCart_shelfItem">
                                                <div class="men-thumb-item">
                                                    <img src="~/Public/images/Products/@proinfo.Img" alt="" class="pro-image-front">
                                                    <img src="~/Public/images/Products/@proinfo.Img" alt="" class="pro-image-back">
                                                    <div class="men-cart-pro">
                                                        <div class="inner-men-cart-pro">
                                                            <a href="~/@proinfo.Slug" class="link-product-add-cart">XEM SẢN PHẨM</a>
                                                        </div>
                                                    </div>
                                                    <span class="product-new-top">New</span>

                                                </div>
                                                <div class="item-info-product ">
                                                    <h4><a href="~/@proinfo.Slug">@proinfo.Name</a></h4>
                                                    <div class="info-product-price">
                                                        <span class="item_price">@string.Format("{0:0,0}", proinfo.Pricesale) <sup>đ</sup></span>
                                                        <del class="text-danger">@string.Format("{0:0,0}", proinfo.Price)</del><sup>đ</sup>
                                                    </div>
                                                    <a href="@Url.Action("CartAdd","Giohang",new { productid = proinfo.Id})" class="item_add single-item hvr-outline-out button2">
                                                        <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i> Mua
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    }

                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    @Html.PagedListPager(Model,page => Url.Action("Product","Site", new { page}))
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- //product-nav -->
        </div>
    </div>

</section>

ThoiTrangGiayCaoCap/Views/Site/ProductCategory.cshtml
@model PagedList.IPagedList<MyClass.Models.ProductInfo>
@{
    var category = ViewBag.Category;
}
@{
    ViewBag.Title = category.Name;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@using PagedList.Mvc;
<section class="maincontent clearfix">
    <div class="container my-3">
        <div class="row">
            @Html.Action("ListCategory", "Module")
            @Html.Action("PostLastNews", "Module")
            <div class="col-md-9">
                <!-- product-nav -->
                <div class="product-easy">
                    <script src="~/Public/js/easyResponsiveTabs.js"></script>
                    <script src="~/Public/js/easyResponsiveTabs.js" type="text/javascript"></script>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $('#horizontalTab').easyResponsiveTabs({
                                type: 'default', //Types: default, vertical, accordion
                                width: 'auto', //auto or any width like 600px
                                fit: true   // 100% fit in a container
                            });
                        });
                    </script>
                    <div class="sap_tabs">
                        <div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
                            <ul class="resp-tabs-list">
                                <li class="resp-tab-item " style="font-weight:700;color:#111b8c;text-transform: uppercase" aria-controls="tab_item-0" role="tab"><span>@category.Name</span></li>
                            </ul>
                            <div class="resp-tabs-container">
                                <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
                                    @foreach (var proinfo in Model)
                                    {
                                        <div class="col-md-4 product-men" style="margin-bottom:30px">
                                            <div class="men-pro-item simpleCart_shelfItem">
                                                <div class="men-thumb-item">
                                                    <img src="~/Public/images/Products/@proinfo.Img" alt="" class="pro-image-front">
                                                    <img src="~/Public/images/Products/@proinfo.Img" alt="" class="pro-image-back">
                                                    <div class="men-cart-pro">
                                                        <div class="inner-men-cart-pro">
                                                            <a href="~/@proinfo.Slug" class="link-product-add-cart">XEM SẢN PHẨM</a>
                                                        </div>
                                                    </div>
                                                    <span class="product-new-top">New</span>

                                                </div>
                                                <div class="item-info-product ">
                                                    <h4><a href="~/@proinfo.Slug">@proinfo.Name</a></h4>
                                                    <div class="info-product-price">
                                                        <span class="item_price">@string.Format("{0:0,0}", proinfo.Pricesale) <sup>đ</sup></span>
                                                        <del class="text-danger">@string.Format("{0:0,0}", proinfo.Price)</del><sup>đ</sup>
                                                    </div>
                                                    <a href="@Url.Action("CartAdd","Giohang",new { productid = proinfo.Id})" class="item_add single-item hvr-outline-out button2">
                                                        <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i> Mua
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    }

                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    @Html.PagedListPager(Model, page => Url.Action("Index", "Site", new { page }))
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- //product-nav -->
        </div>
    </div>

</section>